apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    environment: production
    tier: frontend
    track: stable
  template:
    metadata:
      name: sevtvideo
      labels:
        environment: production
        tier: frontend
        track: stable
    spec:
      containers:
      - name: sevtvideo
        image: tsimao/main:latest
        ports:
        - containerPort: 8080
